dist: xenial
sudo: required

language: go
go:
  - '1.11.x'

services:
  - docker

env:
  global:
    - KUBECTL_VERSION=v1.12.0

jobs:
  include:
    - stage: Verify Go formatting
      script: make verify-gofmt

    - stage: Compile
      script: make compile

    - stage: Tests
      script: make test-ci

    - stage: E2E Tests
      script: make test-e2e
      before_script:
        # Download kubectl, which is a requirement for using kind and running e2e tests.
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download and build kind
        - go get sigs.k8s.io/kind
        # Start kind cluster using default settings
        - kind create cluster
        # Set kubeconfig environment variable
        - export KUBECONFIG="$(kind get kubeconfig-path)"

notifications:
  email: false
  