/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/xmudrii/etcdproxy-controller/pkg/apis/etcd/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EtcdStorageLister helps list EtcdStorages.
type EtcdStorageLister interface {
	// List lists all EtcdStorages in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.EtcdStorage, err error)
	// Get retrieves the EtcdStorage from the index for a given name.
	Get(name string) (*v1alpha1.EtcdStorage, error)
	EtcdStorageListerExpansion
}

// etcdStorageLister implements the EtcdStorageLister interface.
type etcdStorageLister struct {
	indexer cache.Indexer
}

// NewEtcdStorageLister returns a new EtcdStorageLister.
func NewEtcdStorageLister(indexer cache.Indexer) EtcdStorageLister {
	return &etcdStorageLister{indexer: indexer}
}

// List lists all EtcdStorages in the indexer.
func (s *etcdStorageLister) List(selector labels.Selector) (ret []*v1alpha1.EtcdStorage, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.EtcdStorage))
	})
	return ret, err
}

// Get retrieves the EtcdStorage from the index for a given name.
func (s *etcdStorageLister) Get(name string) (*v1alpha1.EtcdStorage, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("etcdstorage"), name)
	}
	return obj.(*v1alpha1.EtcdStorage), nil
}
