// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/xmudrii/etcdproxy-controller/pkg/apis/etcd/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EtcdStorageLister helps list EtcdStorages.
type EtcdStorageLister interface {
	// List lists all EtcdStorages in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.EtcdStorage, err error)
	// Get retrieves the EtcdStorage from the index for a given name.
	Get(name string) (*v1alpha1.EtcdStorage, error)
	EtcdStorageListerExpansion
}

// etcdStorageLister implements the EtcdStorageLister interface.
type etcdStorageLister struct {
	indexer cache.Indexer
}

// NewEtcdStorageLister returns a new EtcdStorageLister.
func NewEtcdStorageLister(indexer cache.Indexer) EtcdStorageLister {
	return &etcdStorageLister{indexer: indexer}
}

// List lists all EtcdStorages in the indexer.
func (s *etcdStorageLister) List(selector labels.Selector) (ret []*v1alpha1.EtcdStorage, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.EtcdStorage))
	})
	return ret, err
}

// Get retrieves the EtcdStorage from the index for a given name.
func (s *etcdStorageLister) Get(name string) (*v1alpha1.EtcdStorage, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("etcdstorage"), name)
	}
	return obj.(*v1alpha1.EtcdStorage), nil
}
