// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/xmudrii/etcdproxy-controller/pkg/client/clientset/versioned/typed/etcd/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeEtcdV1alpha1 struct {
	*testing.Fake
}

func (c *FakeEtcdV1alpha1) EtcdStorages() v1alpha1.EtcdStorageInterface {
	return &FakeEtcdStorages{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeEtcdV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
